name: projeto_final_talp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.2
  curved_navigation_bar: ^1.0.6
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_ui_auth: ^1.16.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.3.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.7.2
  image_picker: ^1.1.2
  motion_tab_bar: ^2.0.4
  riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
